// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lusmncqulwpcaquprcls.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx1c21uY3F1bHdwY2FxdXByY2xzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNzg2NzgsImV4cCI6MjA3MDY1NDY3OH0.LWZVEdD0pwic6AOgcZqPgnCbWQW-UmCw2XUbg93r2M8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});